name: Test Core

on:
  push:
    branches: 
    - master
    - challenge-solutions 
  pull_request:
    branches:
    - master
    - challenge-solutions 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore DataConverter.Core.Tests
    - name: Build
      run: dotnet build DataConverter.Core.Tests --configuration Release --no-restore
    - name: Test
      run: dotnet test DataConverter.Core.Tests --no-restore --verbosity normal
